version: 2
jobs:
  push-update-to-standards-register:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run:
          name: Get standards register configuration
          command: curl -o /tmp/workspace/tmp-register.json https://raw.githubusercontent.com/ddvlanck/OSLO-StandaardenGeneral/master/standaardenregister.json
      - run:
          name: Get latest commit hash of the repository
          command: |
            export COMMIT=$(git rev-parse --verify HEAD)
            echo $COMMIT
  push-to-repository:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "c1:60:33:1c:43:ce:00:5b:66:61:79:8b:67:d4:0c:28"
      - run:
          name: Checkout target repo
          workdir: /tmp
          command: |
            rm -rf OSLO-StandaardenGenerated
            git clone git@github.com:ddvlanck/OSLO-StandaardenGenerated.git
      - run:
          name: Clean the generated directory
          workdir: /tmp/OSLO-StandaardenGenerated
          command: |
            git fetch origin
      #            if [ "`cat /tmp/workspace/haschangedpublications.json`" == "false" ] ; then git rm -r --force * ; fi
      - run:
          name: Copy generated assets
          workdir: /tmp/workspace
          command: |
            mkdir -p /tmp/OSLO-StandaardenGenerated/erkende-standaard
            mkdir -p /tmp/OSLO-StandaardenGenerated/kandidaat-standaard
            mkdir -p /tmp/OSLO-StandaardenGenerated/standaard-in-ontwikkeling
            if [ -d html_pages/erkende-standaard ] ; then if [ ! "$(ls -A html_pages/erkende-standaard)" ] ; then echo "Directory html_pages/erkende-standaard is empty" ; else cp -R html_pages/erkende-standaard/* /tmp/OSLO-StandaardenGenerated/erkende-standaard/ ; fi fi
            if [ -d html_pages/kandidaat-standaard ] ; then if [ ! "$(ls -A html_pages/kandidaat-standaard)" ] ; then echo "Directory html_pages/kandidaat-standaard is empty" ; else cp -R html_pages/kandidaat-standaard/* /tmp/OSLO-StandaardenGenerated/kandidaat-standaard/ ; fi fi
            if [ -d html_pages/standaard-in-ontwikkeling ] ; then if [ ! "$(ls -A html_pages/standaard-in-ontwikkeling)" ] ; then echo "Directory html_pages/standaard-in-ontwikkeling is empty" ; else cp -R html_pages/standaard-in-ontwikkeling/* /tmp/OSLO-StandaardenGenerated/standaard-in-ontwikkeling/ ; fi fi

      - run:
          name: Insert the commit
          command: |
            export TAG=`echo "${CIRCLE_SHA1}"`
            echo "{\"commit\" : \"$TAG\"}" > /tmp/OSLO-StandaardenGenerated/commit.json
      - run:
          name: Push results to Github repository OSLO-Generated
          workdir: /tmp/OSLO-StandaardenGenerated
          command: |
            git config user.email "vanlanckdw@aocsw323"
            git config user.name "Circle CI Builder"
            git add .
            git status
            git commit -m "Applying changes from commit ${CIRCLE_SHA1}" --allow-empty
            export TAG=`echo "${CIRCLE_SHA1}" | cut -c1-15`
            git tag "${TAG}"
            git push --force origin "${CIRCLE_BRANCH}"
            git push --tags
workflows:
  version: 2
  update_standards_register:
    jobs:
      - push-update-to-standards-register
