version: 2
jobs:
  update-standards-register:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: chmod -R 777 $PWD/scripts
      - run: $PWD/scripts/update.sh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - updated-register.json
  push-update:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "54:cc:82:5d:28:07:62:9a:65:1a:c8:68:86:6a:1b:24"
      - run:
          name: Checkout target repo
          workdir: /tmp
          command: |
            rm -rf OSLO-StandaardenGeneral
            git clone git@github.com:ddvlanck/OSLO-StandaardenGeneral.git
      - run:
          name: Clean the directory
          workdir: /tmp/OSLO-StandaardenGeneral
          command: |
            git fetch origin
      - run:
          name: Copy generated assets
          workdir: /tmp/workspace
          command: |
            if [ -f updated-register.json ] ; then cp updated-register.json /tmp/OSLO-StandaardenGeneral/standaardenregister.json ; fi
      - run:
          name: Push results to Github repository OSLO-General
          workdir: /tmp/OSLO-StandaardenGeneral
          command: |
            git config user.email "vanlanckdw@aocsw323"
            git config user.name "Circle CI Builder"
            git add .
            git status
            git commit -m "Applying changes from OSLOtheme repository ${CIRCLE_PROJECT_REPONAME}" --allow-empty
            git push --force origin master
workflows:
  version: 2
  update_standards_register:
    jobs:
      - update-standards-register
      - push-update:
          requires:
            - update-standards-register
